version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: aguas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - 3307:3306
    networks:
      - aguas
    volumes:
      - ./data/mysql:/var/lib/mysql

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - aguas
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=aguas

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - mysql
      - postgres
    networks:
      - aguas
    ports:
        - 9090:8080

volumes:
  mysql-data:
  postgres-data:

networks:
  aguas:
